"""empty message

Revision ID: df38da0b72df
Revises: 
Create Date: 2020-08-31 23:48:51.934694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df38da0b72df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('link_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
